@baseUrl = http://localhost:3333

# GET health
# @name healthCheck
GET {{baseUrl}}/health

###

# GET rooms
# @name getRooms
GET {{baseUrl}}/rooms


###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "Essa é uma sala de teste 03"
}

###

@roomId =  {{createRoom.response.body.$.roomId}}

###
# GET room/questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
  "question": "Qual a velocidade mais rapida já testada pela humanindade?"
}

###